### ISSUE TITLE
Activating extension `swyphcosmo.spellchecker` failed: Path must be a string. Received undefined.

### ISSUE THREAD

**Issue by sean-mcmanus** [swyphcosmo/vscode-spellchecker#10]
VS Code 1.5.3, SpellChecker 1.1.6, Win10.

When I debug our C/C++ extensions without having a project open, I get this error in my target VS Code: "Activating extension `swyphcosmo.spellchecker` failed: Path must be a string. Received undefined.".

Debug console in my debugger VS Code gives the following:

Spellchecker now active!
Activating extension `swyphcosmo.spellchecker` failed: Path must be a string. Received undefined.
Activating extension `swyphcosmo.spellchecker` failed:  Path must be a string. Received undefined
Here is the error stack:  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:506:7)
    at SpellCheckerProvider.getSettings (C:\Users\seanmcm.vscode\extensions\swyphcosmo.spellchecker-1.1.6\out\src\features\SpellCheckerProvider.js:320:52)
    at SpellCheckerProvider.activate (C:\Users\seanmcm.vscode\extensions\swyphcosmo.spellchecker-1.1.6\out\src\features\SpellCheckerProvider.js:19:30)
    at activate (C:\Users\seanmcm.vscode\extensions\swyphcosmo.spellchecker-1.1.6\out\src\extension.js:7:18)
    at Function.t._callActivateOptional (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:22251)
    at Function.t._callActivate (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:22034)
    at f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:21906
    at Object.m [as _notify](f:Program Files %28x86%29Microsoft VS CoderesourcesappoutvsworkbenchnodeextensionHostProcess.js:5:19713)
    at Object.W.enter (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:23291)
    at n.Class.define._run (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:25119)
    at n.Class.define._completed (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:24560)
    at n.Class.derive.join.c (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:28098)
    at n.Class.derive.join.i.forEach.G.then.o.(anonymous function) (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:28315)
    at Object.m [as _notify](f:Program Files %28x86%29Microsoft VS CoderesourcesappoutvsworkbenchnodeextensionHostProcess.js:5:19713)
    at Object.W.enter (f:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:5:23291)

**Comment by swyphcosmo** [comment]
I just found this error myself yesterday. I have fixed it and will get it uploaded later tonight with a couple of other feature additions.

**Comment by sean-mcmanus** [comment]
Cool, thanks.

**Comment by swyphcosmo** [comment]
I just uploaded `v1.2.0` which should fix your problem. Let me know if you run into any other issues.
