### ISSUE TITLE
Activating extension swyphcosmo.spellchecker failed

### ISSUE THREAD

**Issue by artem-sidorenko** [swyphcosmo/vscode-spellchecker#13]
- vscode-spellchecker version 1.2.1
- vscode version 1.6.0
- platform: Linux Mint

I get following in the vscode logs:

```
[Extension Host] Spellchecker now active!
threadService.ts:222 [Extension Host] Activating extension `swyphcosmo.spellchecker` failed: Unexpected token / in JSON at position 795.(anonymous function) @ threadService.ts:222emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
threadService.ts:222 [Extension Host] Activating extension `swyphcosmo.spellchecker` failed:  Unexpected token / in JSON at position 795(anonymous function) @ threadService.ts:222emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
threadService.ts:222 [Extension Host] Here is the error stack:  SyntaxError: Unexpected token / in JSON at position 795
    at Object.parse (native)
    at SpellCheckerProvider.getUserSettings (/home/artem/.vscode/extensions/swyphcosmo.spellchecker-1.2.1/out/src/features/SpellCheckerProvider.js:441:25)
    at SpellCheckerProvider.getSettings (/home/artem/.vscode/extensions/swyphcosmo.spellchecker-1.2.1/out/src/features/SpellCheckerProvider.js:473:37)
    at SpellCheckerProvider.activate (/home/artem/.vscode/extensions/swyphcosmo.spellchecker-1.2.1/out/src/features/SpellCheckerProvider.js:22:30)
    at activate (/home/artem/.vscode/extensions/swyphcosmo.spellchecker-1.2.1/out/src/extension.js:7:18)
    at Function.t._callActivateOptional (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:15169)
    at Function.t._callActivate (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:14952)
    at /opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:13:14824
    at Object.m [as _notify] (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:5002)
    at Object.enter (/opt/vscode/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:8580)
mainThreadExtensionService.ts:89 Activating extension `swyphcosmo.spellchecker` failed: Unexpected token / in JSON at position 795.
```

**Comment by artem-sidorenko** [comment]
The extension works however

**Comment by swyphcosmo** [comment]
I think this is happening because of an error in your vscode user settings file. The line that's causing the error is parsing your settings file from `$HOME/.config/Code/User/settings.json`. If you want to share this file, I can help you fix the issue, but it doesn't seem like it has to do with this extension.

**Comment by artem-sidorenko** [comment]
@swyphcosmo indeed. Шt was related to an issue with another extension I was troubleshooting, and I broke my configuration there. Sorry for the noise
