### ISSUE TITLE
Error: Running the contributed command failed.

### ISSUE THREAD

**Issue by StephenNay** [swyphcosmo/vscode-spellchecker#19]
Spell checker installed fine and underlines words that aren't in the dictionary, but trying to do anything beyond that fails, always with the same error. For example, trying to create a settings file:

Error: Running the contributed command:'spellchecker.createSettingsFile' failed.

I get an equivalent error when I try to tell it to ignore words or add them to the dictionary. However, if I try a second time to add a word to the dictionary, I get an error saying that it's already there.

Permission problem? I would appreciate any tips on resolving this.

Thanks,
Steve

**Comment by swyphcosmo** [comment]
My guess would be a permission problem. That was the only way I was able to recreate your issue on both Windows 10 and Ubuntu 14.04.  Do you have permission to the folder that you're selecting as your workspace?  

Are you able to manually create, modify, and save files within your workspace?

Is the path a network path? I have seen some people talking about weird behavior when accessing folders on a networked drive.

What version of the extension, VSCode, and OS are you using?

When adding words to the dictionary, this extension will first add it to a structure contained in memory, and then attempt to save that structure into the settings file. On the first attempt, the settings file is not created, but the word is still added to the internal structure. On the second attempt, the word is first checked against the structure. Since your word was previously added, you get that error instead of the 'spellchecker.createSettingsFile' error.

I will try to add better handling of the errors within 'spellchecker.createSettingsFile'.

**Comment by swyphcosmo** [comment]
I've just uploaded a patch release (v1.2.3) to provide more output during the configuration file creation process. Hopefully, this will help us track down the problem.

As an example, this is the output I received when trying to create a config file in a directory which I do not have write access to:

```
Spellchecker now active!
Spell checker configuration file not found
Creating file 'c:\Program Files (x86)\gs\.vscode\spellchecker.json'
Saving spell check configuration
c:\Program Files (x86)\gs\.vscode
Error: EPERM: operation not permitted, mkdir 'c:\Program Files (x86)\gs\.vscode'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.exports.wrapFsWithAsar.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (c:\Users\swyph\Documents\Gitlab\VSCode\SpellCheck\vscode-spellchecker\node_modules\mkdirp\index.js:71:13)
    at SpellCheckerProvider.saveWorkspaceSettings (c:\Users\swyph\Documents\Gitlab\VSCode\SpellCheck\vscode-spellchecker\out\src\features\SpellCheckerProvider.js:486:24)
    at SpellCheckerProvider.createSettingsFile (c:\Users\swyph\Documents\Gitlab\VSCode\SpellCheck\vscode-spellchecker\out\src\features\SpellCheckerProvider.js:63:18)
    at t.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:25694)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:10602)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:21356)
    at p (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:22033)
```

Normal operation would provide output like this:

```
Spellchecker now active!
Spell checker configuration file not found
Creating file 'c:\Users\swyph\Downloads\Books\.vscode\spellchecker.json'
Saving spell check configuration
c:\Users\swyph\Downloads\Books\.vscode
```

Please let me know what errors you are seeing. Thanks.

**Comment by swyphcosmo** [comment]
I just merged #20 and released a patch version 1.2.4 to the marketplace. It fixes some possible issues with comments in the settings files. Please check it out, and let me know if you're still having problems with the extension.

**Comment by swyphcosmo** [comment]
@StephenNay Are you still having this issue?

**Comment by swyphcosmo** [comment]
I'm closing this issue due to in activity. If you're still having the issue, feel free to reopen it.
