### ISSUE TITLE
Unable to get spell checker to activiate

### ISSUE THREAD

**Issue by BlairSh** [swyphcosmo/vscode-spellchecker#22]
Getting the following error:

command 'spellchecker.createSettingsFile' not found.  Extension is loaded and as of this date, I am running the latest VS Code release.

**Comment by swyphcosmo** [comment]
Can you enable developer tools (Help -> Toggle developer tools) and let me know what errors you see? If you're using the latest version of this extension (1.2.5), it should give you some more detailed error messages.

**Comment by 4og** [comment]
I have exactly the same issue.

The following errors are shown in the console:
```
[Extension Host] Spellchecker now active!
[Extension Host] Activating extension `swyphcosmo.spellchecker` failed: Unexpected token } in JSON at position 36.
[Extension Host] Activating extension `swyphcosmo.spellchecker` failed:  Unexpected token } in JSON at position 36
[Extension Host] Here is the error stack:  SyntaxError: Unexpected token } in JSON at position 36
    at Object.parse (native)
    at SpellCheckerProvider.getUserSettings (/home/andrey/.vscode/extensions/swyphcosmo.spellchecker-1.2.5/out/src/features/SpellCheckerProvider.js:466:29)
    at SpellCheckerProvider.getSettings (/home/andrey/.vscode/extensions/swyphcosmo.spellchecker-1.2.5/out/src/features/SpellCheckerProvider.js:504:37)
    at SpellCheckerProvider.activate (/home/andrey/.vscode/extensions/swyphcosmo.spellchecker-1.2.5/out/src/features/SpellCheckerProvider.js:23:30)
    at activate (/home/andrey/.vscode/extensions/swyphcosmo.spellchecker-1.2.5/out/src/extension.js:7:18)
    at Function.t._callActivateOptional (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:14861)
    at Function.t._callActivate (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:14644)
    at /opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:14516
    at Object.m [as _notify] (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:5732)
    at Object.enter (/opt/visual-studio-code/resources/app/out/vs/workbench/node/extensionHostProcess.js:6:9310)
Activating extension `swyphcosmo.spellchecker` failed: Unexpected token } in JSON at position 36.
```

**Comment by swyphcosmo** [comment]
@40g would you attach a copy of your `settings.json` file (File -> Preferences -> User Settings)? There seems to be something in that file which isn't parsing correctly.

**Comment by 4og** [comment]
You are right. There was a syntax error in `settings.json` - a superfluous comma before closing brace. After removing it, the spellchecker started to work. The 'Create Spell Checker Settings File' command works fine as well.

**Comment by swyphcosmo** [comment]
@BlairSh Are you still having these issues?

**Comment by BlairSh** [comment]
I uninstalled and installed latest release and it is now working.  

Separate thing I have noticed is no "light bulb" showing for errors.  But otherwise working for me.

**Comment by swyphcosmo** [comment]
That's weird. If you go to Help -> Toggle Developer Tools, is there an error that shows up in the Console view?

I'm not sure how often you use vscode, but I noticed a recent version moved the location of the lightbulb. It shows up on the left side of the window near the line numbers instead of to the right of the word. If you aren't seeing any errors in the Console, perhaps the functionality is just different than what you were used to.

**Comment by swyphcosmo** [comment]
Closing due to inactivity. Feel free to reopen if you are still having problems.
